# Gmail (Sender)
gmail_user = "yachtcodeonline@gmail.com"
gmail_password = "afegbmrtvfqsidkp"

# Email Recipients
alert_emails = ["roadtorunway369@gmail.com", "prajwal.gopinath@gmail.com"]

# Telegram
telegram_token = "8394363327:AAE217HwbHMfP2fJw6NkDEeCjweg5nNIbkI"
telegram_chat_id = "5667632039"
